export { default as benefitsSection } from './benefits-section.png';
export { default as classImage1 } from './class-image-1.png';
export { default as classImage2 } from './class-image-2.png';
export { default as classImage3 } from './class-image-3.png';
export { default as classImage4 } from './class-image-4.png';
export { default as classImage5 } from './class-image-5.png';
export { default as classImage6 } from './class-image-6.png';
export { default as contactUsSection } from './contact-us-section.png';
export { default as logo } from './logo.png';
